source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Practice' do
pod 'SnapKit', '~>3.0.2'
pod 'Alamofire','~>4.0'
pod 'RxSwift'
pod 'RxCocoa'
pod 'Action'

end
